---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:

      - recipe[vsoagent::default]

    attributes:
      vsoagent:
          vm_user: "vagrant"
          vm_group: "vagrant"
